---
resource_types:
- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: greenplum-database-release
  type: git
  icon: git
  source:
    uri: https://github.com/greenplum-db/greenplum-database-release.git
    branch: debian-packaging

- name: ubuntu-bionic
  type: docker-image
  icon: docker
  source:
    repository: ubuntu
    tag: "18.04"

- name: debian-stable
  type: docker-image
  icon: docker
  source:
    repository: debian
    tag: stable

- name: libgpopt3
  type: gcs
  icon: package
  source:
    bucket: gp-releng-scratch
    json_key: ((gp-releng-scratch-gcs-key))
    regexp: dev/binary/libgpopt3_(.*)_amd64.deb

- name: libgpopt3-dev
  type: gcs
  icon: package
  source:
    bucket: gp-releng-scratch
    json_key: ((gp-releng-scratch-gcs-key))
    regexp: dev/binary/libgpopt3-dev_(.*)_amd64.deb

- name: greenplum-db
  type: gcs
  icon: package
  source:
    bucket: gp-releng-scratch
    json_key: ((gp-releng-scratch-gcs-key))
    regexp: dev/binary/greenplum-db_(.*)_amd64.deb

jobs:
- name: build gporca packages
  plan:
  - in_parallel:
    - get: greenplum-database-release
      trigger: true
    - get: debian-stable
    - get: ubuntu-bionic
  - in_parallel:
    - task: build ubuntu-bionic binary package
      file: greenplum-database-release/packaging/ci/concourse/build-debian-package/task.yml
      image: ubuntu-bionic
      params:
        PKG_NAME: gporca
      output_mapping: {debian-packages: bionic-debian-packages}
    - task: build debian-stable binary package
      file: greenplum-database-release/packaging/ci/concourse/build-debian-package/task.yml
      image: debian-stable
      params:
        PKG_NAME: gporca
  - in_parallel:
    - put: libgpopt3
      params:
        file: bionic-debian-packages/libgpopt3_*.deb
    - put: libgpopt3-dev
      params:
        file: bionic-debian-packages/libgpopt3-dev_*.deb

- name: build gpdb packages
  plan:
  - in_parallel:
    - get: greenplum-database-release
      passed: [build gporca packages]
    - get: libgpopt3
      passed: [build gporca packages]
    - get: libgpopt3-dev
      passed: [build gporca packages]
    - get: debian-stable
    - get: ubuntu-bionic
  - in_parallel:
    - task: build ubuntu-bionic binary package
      file: greenplum-database-release/packaging/ci/concourse/build-gpdb-debian-package/task.yml
      image: ubuntu-bionic
      params:
        PKG_NAME: gpdb
      output_mapping: {debian-packages: bionic-gpdb-debian-packages}
    - task: build debian-stable binary package
      file: greenplum-database-release/packaging/ci/concourse/build-gpdb-debian-package/task.yml
      image: debian-stable
      params:
        PKG_NAME: gpdb
  - put: greenplum-db
    params:
      file: bionic-gpdb-debian-packages/greenplum-db_*.deb
